#!/usr/bin/env node
/*
 * Refreshes src/lib/tlds.js from the IANA root zone list. Run occasionally
 * (`npm run update-tlds`); the toolkit itself never goes online.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const SOURCE = 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt';
const OUT = path.join(__dirname, '..', 'src', 'lib', 'tlds.js');

(async () => {
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`HTTP ${res.status} from ${SOURCE}`);
  const lines = (await res.text()).split(/\r?\n/);
  const version = (lines[0].match(/Version \d+/) || ['unknown version'])[0];
  const tlds = lines.filter((l) => l && !l.startsWith('#')).map((l) => l.trim().toLowerCase());
  if (tlds.length < 1000 || !tlds.includes('com')) throw new Error(`Unexpected list (${tlds.length} entries)`);

  // Wrapped at ~100 characters per line so diffs stay readable.
  const rows = [];
  let row = '';
  for (const t of tlds) {
    if (row.length + t.length > 100) { rows.push(row.trim()); row = ''; }
    row += t + ' ';
  }
  rows.push(row.trim());

  const js = `/*
 * IANA top-level domains (${tlds.length} entries, ${version}).
 * Generated by scripts/update-tlds.js from ${SOURCE}. Do not edit by hand.
 */
(function (root, list) {
  const tlds = new Set(list.join(' ').split(' '));
  if (typeof module === 'object' && module.exports) module.exports = tlds;
  else (root.OAT = root.OAT || {}).tlds = tlds;
})(globalThis, [
${rows.map((r) => `  '${r}',`).join('\n')}
]);
`;
  fs.writeFileSync(OUT, js);
  console.log(`Wrote ${path.relative(process.cwd(), OUT)}: ${tlds.length} TLDs (${version})`);
})().catch((e) => { console.error(e.message); process.exitCode = 1; });
